server:
  port: 9809


spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

work:
  queue:
      input: reportq-in
      output: reportq-out
    

#Propiedades de  configuracion para el Message Broker
jms:
  cache:
    size: 10

     

    